name: Deploy React App
permissions:
  contents: write
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v4

      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install
        working-directory: react-app

      - name: Run tests
        run: npm run test
        working-directory: react-app

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.1.1
        with:
          folder: build # The folder the action should deploy.
          branch: gh-pages
        env:
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}